image: python:3.12-slim

stages:
  - install
  - lint
  - release

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pypoetry"
  POETRY_VIRTUALENVS_IN_PROJECT: "true"
  VENV_PATH: "$CI_PROJECT_DIR/.venv"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip
    - .cache/pypoetry
    - .venv

before_script:
  - python3 -V
  - pip install --upgrade pip
  - pip install poetry
  - poetry install --no-root

.install_template: &install_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

install:
  stage: install
  <<: *install_template
  script:
    - poetry install
  artifacts:
    paths:
      - .venv

lint:
  stage: lint
  <<: *install_template
  script:
    - poetry run ruff check . --exit-zero

release:
  stage: release
  <<: *install_template
  script:
    - apt-get update && apt-get install zip -y
    - zip -r cortex-mcp.zip src Dockerfile pyproject.toml poetry.lock
    - sha256sum cortex-mcp.zip > cortex-mcp.zip.sha256
  artifacts:
    paths:
      - cortex-mcp.zip
      - cortex-mcp.zip.sha256
    expire_in: 1 week
include:
  - project: shared-services/gitlab-ci-templates
    ref: master
    file:
      - templates/Jobs/Security/secure-cicd.yml
