import logging
from typing import Annotated, Optional

from fastmcp import Context, FastMCP
from pydantic import Field

from entities.exceptions import (
    PAPIAuthenticationError,
    PAPIClientError,
    PAPIClientRequestError,
    PAPIConnectionError,
    PAPIResponseError,
    PAPIServerError,
)
from pkg.util import create_response
from usecase.base_module import BaseModule
from usecase.fetcher import get_fetcher

logger = logging.getLogger(__name__)


async def insert_correlation_rule(
    ctx: Context,
    name: Annotated[str, Field(description="Display name of the correlation rule")],
    xql_query: Annotated[str, Field(description="XQL query that defines the detection logic. Must be valid XQL syntax starting with dataset specification.")],
    severity: Annotated[str, Field(description="Alert severity level generated by this rule")],
    alert_name: Annotated[str, Field(description="Name assigned to alerts generated by this rule")],
    alert_category: Annotated[str, Field(description="MITRE ATT&CK tactic/category for alerts")],
    is_enabled: Annotated[bool, Field(description="Whether the rule is active and generating alerts")] = True,
    description: Annotated[str, Field(description="Detailed description of what the rule detects and when it triggers")] = "",
    alert_description: Annotated[str, Field(description="Description shown in the alert when rule triggers")] = "",
    execution_mode: Annotated[str, Field(description="Execution mode for the rule (must be SCHEDULED)")] = "SCHEDULED",
    search_window: Annotated[str, Field(description="Time window for query execution (e.g., '10 minutes', '1 hours', '24 hours', '7 days')")] = "1 hours",
    timezone: Annotated[str, Field(description="Timezone for scheduling (e.g., 'UTC', 'America/New_York')")] = "UTC",
    crontab: Annotated[str, Field(description="Crontab expression for advanced scheduling (optional)")] = "",
    suppression_enabled: Annotated[bool, Field(description="Enable alert suppression to prevent duplicate alerts")] = True,
    suppression_duration: Annotated[str, Field(description="How long to suppress duplicate alerts (e.g., '24 hours')")] = "24 hours",
    suppression_fields: Annotated[list, Field(description="Fields to use for deduplication (e.g., ['actor_effective_username', 'action_remote_ip'])")] = [],
    rule_id: Annotated[Optional[int], Field(description="Unique numeric rule ID. Only provide to UPDATE an existing rule. Omit for new rules.")] = None,
) -> str:
    """
    Insert or update XSIAM Correlation Rule.

    Correlation Rules are XQL-based detection rules that continuously analyze incoming data
    and generate alerts when suspicious patterns or conditions are detected. These rules are
    the foundation of custom threat detection in XSIAM.

    Use this tool to:
    - Create custom detection rules for specific threats
    - Update existing correlation rules to refine detection logic
    - Implement organization-specific security policies
    - Build automated alerting for attack patterns
    - Deploy detections based on threat intelligence
    - Adjust rule sensitivity and thresholds

    Common use cases:
    - Detecting lateral movement patterns
    - Identifying credential abuse and privilege escalation
    - Detecting data exfiltration attempts
    - Monitoring for specific IOCs or TTPs
    - Custom compliance and policy violations
    - Multi-stage attack detection
    - Behavioral anomaly detection

    Rule Operation:
    - Rules execute continuously (REAL_TIME) or on schedule (SCHEDULED)
    - Each rule uses an XQL query to analyze data
    - When query conditions match, an alert is automatically generated
    - Alerts include the severity, category, and metadata you specify
    - Rules can be enabled/disabled without deletion

    Severity Levels (severity parameter):
    - SEV_010_INFO: Informational alerts for awareness
    - SEV_020_LOW: Low-severity findings requiring minimal attention
    - SEV_030_MEDIUM: Medium-severity threats needing investigation
    - SEV_040_HIGH: High-severity threats requiring immediate response

    Alert Categories (alert_category parameter):
    - OTHER: Uncategorized alerts
    - PERSISTENCE: Maintaining foothold mechanisms
    - EVASION: Avoiding detection and security controls
    - TAMPERING: Modifying data or configurations
    - FILE_TYPE_OBFUSCATION: Hiding file types
    - PRIVILEGE_ESCALATION: Gaining higher-level permissions
    - CREDENTIAL_ACCESS: Stealing credentials and authentication
    - LATERAL_MOVEMENT: Moving through the environment
    - EXECUTION: Running malicious code
    - COLLECTION: Gathering data of interest
    - EXFILTRATION: Data theft and extraction
    - INFILTRATION: Unauthorized entry
    - DROPPER: Malware delivery
    - FILE_PRIVILEGE_MANIPULATION: Changing file permissions
    - RECONNAISSANCE: Active scanning, information gathering
    - DISCOVERY: Network and system reconnaissance

    Execution Modes (execution_mode parameter):
    - SCHEDULED: Periodic execution at defined intervals
      - Requires: search_window (e.g., "10 minutes", "1 hours")
      - Requires: crontab expression (e.g., "*/10 * * * *" for every 10 min)
    - REAL_TIME: Continuous real-time monitoring
      - No schedule parameters needed (search_window, crontab ignored)
      - Processes events as they arrive

    XQL Query Requirements:
    - Must start with dataset specification (e.g., "dataset = xdr_data")
    - Should include appropriate filters to reduce false positives
    - Use aggregations to detect patterns over time (SCHEDULED mode)
    - REAL_TIME mode: Cannot use LIMIT clause
    - Test queries with run_xql_query before creating rules

    Example XQL queries:
    - Brute force detection: "dataset = xdr_data | filter event_type = ENUM.AUTHENTICATION and outcome = ENUM.FAILED | comp count() by user | filter count > 10"
    - Suspicious process: "dataset = xdr_data | filter event_type = ENUM.PROCESS and action_process_image_name contains 'powershell' and action_process_command_line contains 'bypass'"
    - Data exfiltration: "dataset = xdr_data | filter event_type = ENUM.NETWORK and action_upload_bytes > 100000000"

    Rule ID Management:
    - If rule_id exists: Updates the existing rule with new parameters
    - If rule_id is new: Creates a new correlation rule
    - Use unique IDs to avoid conflicts (consider using timestamp-based IDs)
    - Track rule IDs in your documentation for management

    Best Practices:
    - Start with is_enabled=False to test before activating
    - Use descriptive names that indicate what's being detected
    - Include detailed descriptions for future reference
    - Set appropriate search_window based on detection logic
    - Test XQL queries thoroughly before deployment
    - Monitor for false positives after activation
    - Use severity levels consistently across rules

    Args:
        ctx: The FastMCP context.
        rule_id: Unique numeric rule ID. Updates if exists, creates if new. Omit for new rules.
        name: Display name of the correlation rule (descriptive, clear).
        xql_query: XQL query that defines the detection logic. Must be valid XQL.
        severity: Alert severity level (SEV_010_INFO, SEV_020_LOW, SEV_030_MEDIUM, SEV_040_HIGH).
        alert_name: Name assigned to alerts generated by this rule.
        alert_category: MITRE ATT&CK tactic/category (DISCOVERY, EXECUTION, LATERAL_MOVEMENT, etc.).
        is_enabled: Whether the rule is active and generating alerts (default: True).
        description: Detailed description of what the rule detects (optional but recommended).
        alert_description: Description shown in the alert when rule triggers (default: "").
        execution_mode: Execution mode - SCHEDULED or REAL_TIME (default: SCHEDULED).
        search_window: Time window for query execution, minimum 10 minutes (default: "1 hours").
        timezone: Timezone for scheduling (default: "UTC").
        crontab: Crontab expression for advanced scheduling (default: "").
        suppression_enabled: Enable alert suppression to prevent duplicates (default: True).
        suppression_duration: How long to suppress duplicate alerts (default: "24 hours").
        suppression_fields: Fields to use for deduplication (default: []).

    Returns:
        JSON response with rule creation/update status:
        - added_objects: Number of new rules created
        - updated_objects: Number of existing rules updated
        - errors: Any errors encountered during operation
        - rule_details: Confirmation of rule configuration

    Example Usage:
        # SCHEDULED: Detect risky software installations (runs every hour)
        insert_correlation_rule(
            ctx=ctx,
            name="AnyDesk Installation on endpoint",
            xql_query=\"\"\"config case_sensitive = false | dataset = host_inventory
                | fields applications, host_name, os_type
                | filter applications != null and os_type = ENUM.OS_WINDOWS
                | arrayexpand applications
                | alter app_name = applications -> application_name,
                       app_vendor = applications -> vendor,
                       uninstall_cmd = applications -> uninstall_string
                | filter app_name contains "anydesk" or app_vendor contains "anydesk"
                | fields host_name, app_name, app_vendor, uninstall_cmd\"\"\",
            severity="SEV_040_HIGH",
            alert_name="AnyDesk found on endpoint",
            alert_category="EXECUTION",
            alert_description="AnyDesk version found installed on $host_name",
            is_enabled=False,
            description="Triggers alert when AnyDesk remote access tool is detected",
            execution_mode="SCHEDULED",
            search_window="1 hours",
            crontab="0 * * * *"
        )

        # SCHEDULED: Port scan detection (runs every 10 minutes)
        insert_correlation_rule(
            ctx=ctx,
            name="Noisy Port Scan Detection",
            xql_query=\"\"\"dataset = xdr_data
                | filter event_type = ENUM.NETWORK
                | comp count(distinct action_remote_port) as counter by action_local_ip, action_remote_ip
                | filter counter > 30\"\"\",
            severity="SEV_030_MEDIUM",
            alert_name="Port Scan Detected",
            alert_category="RECONNAISSANCE",
            alert_description="Port Scan from $action_local_ip to $action_remote_ip over $counter ports",
            is_enabled=False,
            description="Detect port scans over 30 ports in 10 minutes",
            execution_mode="SCHEDULED",
            search_window="10 minutes",
            crontab="*/10 * * * *",
            suppression_enabled=True,
            suppression_duration="1 hours"
        )

        # REAL_TIME: Detect portable AnyDesk execution (continuous monitoring)
        insert_correlation_rule(
            ctx=ctx,
            name="Portable AnyDesk Detected",
            xql_query=\"\"\"config case_sensitive = false | dataset = xdr_data
                | filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
                  and action_process_signature_vendor contains "anydesk"
                | alter category = "Threat Detection"
                | fields action_process_image_name, agent_hostname, category\"\"\",
            severity="SEV_030_MEDIUM",
            alert_name="Portable AnyDesk Detected",
            alert_category="EXECUTION",
            alert_description="Portable AnyDesk execution detection",
            is_enabled=False,
            description="Real-time detection of portable AnyDesk executions",
            execution_mode="REAL_TIME"
        )

        # Update an existing rule by providing rule_id
        insert_correlation_rule(
            ctx=ctx,
            rule_id=35,
            name="Port Scan Detection - Enhanced",
            xql_query="...",
            severity="SEV_040_HIGH",
            alert_name="Port Scan Detected",
            alert_category="RECONNAISSANCE",
            is_enabled=True,
            description="Enhanced with lower threshold"
        )
    """

    # Validate minimum search window (must be at least 10 minutes)
    if search_window and ("5 min" in search_window.lower() or "1 min" in search_window.lower()):
        logger.warning(f"Search window '{search_window}' is too short. Adjusting to '10 minutes'.")
        search_window = "10 minutes"

    # Extract dataset name from XQL query (e.g., "dataset = xdr_data" -> "xdr_data")
    dataset_name = "xdr_data"  # default
    if "dataset" in xql_query.lower():
        import re
        match = re.search(r'dataset\s*=\s*(\w+)', xql_query, re.IGNORECASE)
        if match:
            dataset_name = match.group(1)

    # Build the correlation rule payload with all required fields
    # Handle REAL_TIME vs SCHEDULED mode differences
    if execution_mode == "REAL_TIME":
        schedule_crontab = None
        schedule_window = None
        simple_sched = ""  # Empty string for REAL_TIME
    else:
        schedule_crontab = crontab if crontab else "0 * * * *"  # Default: every hour
        schedule_window = search_window
        simple_sched = search_window

    rule_payload = {
        "name": name,
        "severity": severity,
        "xql_query": xql_query,
        "is_enabled": is_enabled,  # boolean
        "description": description,
        "alert_name": alert_name,
        "alert_category": alert_category,
        "alert_description": alert_description,
        "execution_mode": execution_mode,
        "search_window": schedule_window,
        "simple_schedule": simple_sched,  # Required field
        "timezone": timezone,
        "crontab": schedule_crontab,
        "dataset": "alerts",
        "action": "ALERTS",
        "alert_domain": "DOMAIN_SECURITY",
        "alert_type": None,
        "lookup_mapping": None,
        "mapping_strategy": "AUTO",
        "suppression_enabled": suppression_enabled,
        "suppression_duration": suppression_duration if suppression_enabled else None,
        "suppression_fields": suppression_fields if suppression_fields else None,
        "alert_fields": {},
        "user_defined_severity": None,
        "user_defined_category": None,
        "mitre_defs": {},
        "investigation_query_link": None,
        "drilldown_query_timeframe": "ALERT"
    }

    # Only include rule_id for UPDATES (when rule_id is provided)
    if rule_id is not None:
        rule_payload["rule_id"] = rule_id
        logger.info(f"Updating correlation rule: rule_id={rule_id}, name='{name}', enabled={is_enabled}")
    else:
        logger.info(f"Creating new correlation rule: name='{name}', enabled={is_enabled}")

    # For REAL_TIME mode, set schedule fields to null
    if execution_mode == "REAL_TIME":
        rule_payload["simple_schedule"] = None
        rule_payload["search_window"] = None
        rule_payload["crontab"] = None
        rule_payload["timezone"] = None
        rule_payload["lookup_mapping"] = None
        rule_payload["alert_type"] = None

    # Build payload - API expects request_data wrapper with array of rules
    payload = {"request_data": [rule_payload]}

    logger.debug(f"Correlation rule payload: {payload}")

    try:
        fetcher = await get_fetcher(ctx)
        response_data = await fetcher.send_request(
            "/public_api/v1/correlations/insert",
            data=payload
        )

        logger.info(f"Correlation rule operation response: {response_data}")

        # Enhance response with confirmation details
        if isinstance(response_data, dict):
            response_data["rule_details"] = {
                "rule_id": rule_id,
                "name": name,
                "is_enabled": is_enabled,
                "severity": severity,
                "alert_category": alert_category,
                "execution_mode": execution_mode,
            }

        return create_response(data=response_data)

    except (
        PAPIConnectionError,
        PAPIAuthenticationError,
        PAPIServerError,
        PAPIClientRequestError,
        PAPIResponseError,
        PAPIClientError,
    ) as e:
        logger.exception(f"PAPI error while inserting correlation rule: {e}")
        return create_response(data={"error": str(e)}, is_error=True)
    except Exception as e:
        logger.exception(f"Failed to insert correlation rule: {e}")
        return create_response(data={"error": str(e)}, is_error=True)


async def search_correlation_rules(
    ctx: Context,
    filters: Annotated[Optional[list | str], Field(
        description='Filters for searching rules. Example: [{"field": "name", "operator": "contains", "value": "brute"}]. '
                    'Leave empty to get all rules.'
    )] = None,
    search_from: Annotated[int, Field(description="Pagination start offset")] = 0,
    search_to: Annotated[int, Field(description="Pagination end offset")] = 50,
) -> str:
    """Search and list correlation rules. Returns rule names, IDs, status, severity, and XQL queries.
    Use this to find existing rules before creating new ones or to audit detection coverage."""
    import json as _json
    if isinstance(filters, str):
        filters = _json.loads(filters)
    try:
        fetcher = await get_fetcher(ctx)
        payload = {"request_data": {"search_from": search_from, "search_to": search_to}}
        if filters:
            payload["request_data"]["filters"] = filters
        response = await fetcher.send_request("/public_api/v1/correlations/get", data=payload)
        return create_response(data=response)
    except (PAPIConnectionError, PAPIAuthenticationError, PAPIServerError,
            PAPIClientRequestError, PAPIResponseError, PAPIClientError) as e:
        return create_response(data={"error": str(e)}, is_error=True)
    except Exception as e:
        logger.exception(f"Failed to search correlation rules: {e}")
        return create_response(data={"error": str(e)}, is_error=True)


async def get_correlation_rule(
    ctx: Context,
    rule_id: Annotated[int | str, Field(description="Numeric ID of the correlation rule")],
) -> str:
    """Get a specific correlation rule by ID. Returns full rule details including XQL query,
    severity, schedule, suppression settings, and alert configuration."""
    try:
        fetcher = await get_fetcher(ctx)
        response = await fetcher.send_request(
            "/public_api/v1/correlations/get",
            data={"request_data": {"filters": [{"field": "rule_id", "operator": "in", "value": [int(rule_id)]}]}}
        )
        return create_response(data=response)
    except (PAPIConnectionError, PAPIAuthenticationError, PAPIServerError,
            PAPIClientRequestError, PAPIResponseError, PAPIClientError) as e:
        return create_response(data={"error": str(e)}, is_error=True)
    except Exception as e:
        logger.exception(f"Failed to get correlation rule {rule_id}: {e}")
        return create_response(data={"error": str(e)}, is_error=True)


async def delete_correlation_rule(
    ctx: Context,
    rule_id: Annotated[int, Field(description="Numeric ID of the correlation rule to delete")],
    confirm_destructive_action: Annotated[bool, Field(
        description="REQUIRED: Must be True. Permanently deletes a correlation rule."
    )] = False,
) -> str:
    """DESTRUCTIVE: Delete a correlation rule by ID. This cannot be undone.
    Use search_correlation_rules to find the rule ID first."""
    if not confirm_destructive_action:
        return create_response(
            data={
                "error": "Destructive action not confirmed",
                "message": "This permanently deletes a correlation rule. "
                           "Set confirm_destructive_action=True to proceed.",
                "risk_level": "HIGH",
                "reversible": False
            },
            is_error=True
        )
    try:
        fetcher = await get_fetcher(ctx)
        response = await fetcher.send_request(
            "/public_api/v1/correlations/delete",
            data={"request_data": {"filters": [{"field": "rule_id", "operator": "EQ", "value": int(rule_id)}]}}
        )
        return create_response(data={"rule_id": rule_id, "status": "deleted", "response": response})
    except (PAPIConnectionError, PAPIAuthenticationError, PAPIServerError,
            PAPIClientRequestError, PAPIResponseError, PAPIClientError) as e:
        return create_response(data={"error": str(e)}, is_error=True)
    except Exception as e:
        logger.exception(f"Failed to delete correlation rule {rule_id}: {e}")
        return create_response(data={"error": str(e)}, is_error=True)


class CorrelationRulesModule(BaseModule):
    """
    Module for managing XSIAM Correlation Rules (CRUD).

    Tools provided:
        - insert_correlation_rule: Create or update detection rules
        - search_correlation_rules: Search and list existing rules
        - get_correlation_rule: Get a specific rule by ID
        - delete_correlation_rule: Delete a rule by ID
    """

    def register_tools(self):
        self._add_tool(insert_correlation_rule)
        self._add_tool(search_correlation_rules)
        self._add_tool(get_correlation_rule)
        self._add_tool(delete_correlation_rule)

    def register_resources(self):
        pass

    def __init__(self, mcp: FastMCP):
        super().__init__(mcp)
