import logging
from typing import Annotated, Optional

from fastmcp import Context, FastMCP
from pydantic import Field

from entities.exceptions import (
    PAPIAuthenticationError,
    PAPIClientError,
    PAPIClientRequestError,
    PAPIConnectionError,
    PAPIResponseError,
    PAPIServerError,
)
from pkg.util import create_response
from usecase.base_module import BaseModule
from usecase.fetcher import get_fetcher

logger = logging.getLogger(__name__)


async def insert_correlation_rule(
    ctx: Context,
    rule_id: Annotated[int, Field(description="Unique numeric rule ID. Updates if exists, creates if new.")],
    name: Annotated[str, Field(description="Display name of the correlation rule")],
    xql_query: Annotated[str, Field(description="XQL query that defines the detection logic. Must be valid XQL syntax starting with dataset specification.")],
    severity: Annotated[str, Field(description="Alert severity level generated by this rule")],
    alert_name: Annotated[str, Field(description="Name assigned to alerts generated by this rule")],
    alert_category: Annotated[str, Field(description="MITRE ATT&CK tactic/category for alerts")],
    is_enabled: Annotated[bool, Field(description="Whether the rule is active and generating alerts")] = True,
    description: Annotated[str, Field(description="Detailed description of what the rule detects and when it triggers")] = "",
    execution_mode: Annotated[str, Field(description="Execution mode for the rule")] = "REAL_TIME",
    search_window: Annotated[str, Field(description="Time window for query execution (e.g., '1 hours', '24 hours', '7 days')")] = "1 hours",
) -> str:
    """
    Insert or update XSIAM Correlation Rule.

    Correlation Rules are XQL-based detection rules that continuously analyze incoming data
    and generate alerts when suspicious patterns or conditions are detected. These rules are
    the foundation of custom threat detection in XSIAM.

    Use this tool to:
    - Create custom detection rules for specific threats
    - Update existing correlation rules to refine detection logic
    - Implement organization-specific security policies
    - Build automated alerting for attack patterns
    - Deploy detections based on threat intelligence
    - Adjust rule sensitivity and thresholds

    Common use cases:
    - Detecting lateral movement patterns
    - Identifying credential abuse and privilege escalation
    - Detecting data exfiltration attempts
    - Monitoring for specific IOCs or TTPs
    - Custom compliance and policy violations
    - Multi-stage attack detection
    - Behavioral anomaly detection

    Rule Operation:
    - Rules execute continuously (REAL_TIME) or on schedule (SCHEDULED)
    - Each rule uses an XQL query to analyze data
    - When query conditions match, an alert is automatically generated
    - Alerts include the severity, category, and metadata you specify
    - Rules can be enabled/disabled without deletion

    Severity Levels (severity parameter):
    - SEV_010_INFORMATIONAL: Informational alerts for awareness
    - SEV_020_LOW: Low-severity findings requiring minimal attention
    - SEV_030_MEDIUM: Medium-severity threats needing investigation
    - SEV_040_HIGH: High-severity threats requiring immediate response
    - SEV_050_CRITICAL: Critical threats demanding urgent action

    Alert Categories (alert_category parameter):
    MITRE ATT&CK tactics aligned with detection:
    - RECONNAISSANCE: Active scanning, information gathering
    - RESOURCE_DEVELOPMENT: Establishing resources for attacks
    - INITIAL_ACCESS: Entry point techniques (phishing, exploits)
    - EXECUTION: Running malicious code
    - PERSISTENCE: Maintaining foothold mechanisms
    - PRIVILEGE_ESCALATION: Gaining higher-level permissions
    - DEFENSE_EVASION: Avoiding detection and security controls
    - CREDENTIAL_ACCESS: Stealing credentials and authentication
    - DISCOVERY: Network and system reconnaissance
    - LATERAL_MOVEMENT: Moving through the environment
    - COLLECTION: Gathering data of interest
    - COMMAND_AND_CONTROL: C2 communication channels
    - EXFILTRATION: Data theft and extraction
    - IMPACT: Disruption, destruction, or manipulation

    Execution Modes (execution_mode parameter):
    - REAL_TIME: Continuous analysis of streaming data (default, recommended)
    - SCHEDULED: Periodic execution at defined intervals

    XQL Query Requirements:
    - Must start with dataset specification (e.g., "dataset = xdr_data")
    - Should include appropriate filters to reduce false positives
    - Use aggregations to detect patterns over time
    - Include LIMIT clause to prevent performance issues
    - Test queries with run_xql_query before creating rules

    Example XQL queries:
    - Brute force detection: "dataset = xdr_data | filter event_type = ENUM.AUTHENTICATION and outcome = ENUM.FAILED | comp count() by user | filter count > 10"
    - Suspicious process: "dataset = xdr_data | filter event_type = ENUM.PROCESS and action_process_image_name contains 'powershell' and action_process_command_line contains 'bypass'"
    - Data exfiltration: "dataset = xdr_data | filter event_type = ENUM.NETWORK and action_upload_bytes > 100000000"

    Rule ID Management:
    - If rule_id exists: Updates the existing rule with new parameters
    - If rule_id is new: Creates a new correlation rule
    - Use unique IDs to avoid conflicts (consider using timestamp-based IDs)
    - Track rule IDs in your documentation for management

    Best Practices:
    - Start with is_enabled=False to test before activating
    - Use descriptive names that indicate what's being detected
    - Include detailed descriptions for future reference
    - Set appropriate search_window based on detection logic
    - Test XQL queries thoroughly before deployment
    - Monitor for false positives after activation
    - Use severity levels consistently across rules

    Args:
        ctx: The FastMCP context.
        rule_id: Unique numeric rule ID. Updates if exists, creates if new.
        name: Display name of the correlation rule (descriptive, clear).
        xql_query: XQL query that defines the detection logic. Must be valid XQL.
        severity: Alert severity level (SEV_010_INFORMATIONAL, SEV_020_LOW, SEV_030_MEDIUM, SEV_040_HIGH, SEV_050_CRITICAL).
        alert_name: Name assigned to alerts generated by this rule.
        alert_category: MITRE ATT&CK tactic/category (DISCOVERY, EXECUTION, LATERAL_MOVEMENT, etc.).
        is_enabled: Whether the rule is active and generating alerts (default: True).
        description: Detailed description of what the rule detects (optional but recommended).
        execution_mode: Execution mode - REAL_TIME or SCHEDULED (default: REAL_TIME).
        search_window: Time window for query execution (default: "1 hours").

    Returns:
        JSON response with rule creation/update status:
        - added_objects: Number of new rules created
        - updated_objects: Number of existing rules updated
        - errors: Any errors encountered during operation
        - rule_details: Confirmation of rule configuration

    Example Usage:
        # Create a brute force detection rule
        insert_correlation_rule(
            ctx=ctx,
            rule_id=10001,
            name="SSH Brute Force Detection",
            xql_query="dataset = xdr_data | filter event_type = ENUM.AUTHENTICATION and action_service_name = 'SSH' and outcome = ENUM.FAILED | comp count() by source_ip, user | filter count > 5",
            severity="SEV_040_HIGH",
            alert_name="SSH Brute Force Attempt Detected",
            alert_category="CREDENTIAL_ACCESS",
            is_enabled=True,
            description="Detects multiple failed SSH authentication attempts from the same IP to the same user account, indicating potential brute force attack",
            execution_mode="REAL_TIME",
            search_window="5 minutes"
        )

        # Update an existing rule to refine detection
        insert_correlation_rule(
            ctx=ctx,
            rule_id=10001,
            name="SSH Brute Force Detection - Enhanced",
            xql_query="dataset = xdr_data | filter event_type = ENUM.AUTHENTICATION and action_service_name = 'SSH' and outcome = ENUM.FAILED | comp count() by source_ip, user | filter count > 10 and count < 100",
            severity="SEV_040_HIGH",
            alert_name="SSH Brute Force Attempt Detected",
            alert_category="CREDENTIAL_ACCESS",
            is_enabled=True,
            description="Enhanced detection with threshold refinement to reduce false positives from automated scanners",
            execution_mode="REAL_TIME",
            search_window="10 minutes"
        )
    """

    # Build the correlation rule payload
    payload = {
        "request_data": {
            "rules": [
                {
                    "rule_id": rule_id,
                    "name": name,
                    "search_query": xql_query,
                    "severity": severity,
                    "alert_name": alert_name,
                    "alert_category": alert_category,
                    "is_enabled": is_enabled,
                    "description": description,
                    "execution_mode": execution_mode,
                    "search_window": search_window,
                }
            ]
        }
    }

    logger.info(f"Inserting/updating correlation rule: rule_id={rule_id}, name='{name}', enabled={is_enabled}")
    logger.debug(f"Correlation rule payload: {payload}")

    try:
        fetcher = await get_fetcher(ctx)
        response_data = await fetcher.send_request(
            "/public_api/v1/correlations/insert",
            data=payload
        )

        logger.info(f"Correlation rule operation response: {response_data}")

        # Enhance response with confirmation details
        if isinstance(response_data, dict):
            response_data["rule_details"] = {
                "rule_id": rule_id,
                "name": name,
                "is_enabled": is_enabled,
                "severity": severity,
                "alert_category": alert_category,
                "execution_mode": execution_mode,
            }

        return create_response(data=response_data)

    except (
        PAPIConnectionError,
        PAPIAuthenticationError,
        PAPIServerError,
        PAPIClientRequestError,
        PAPIResponseError,
        PAPIClientError,
    ) as e:
        logger.exception(f"PAPI error while inserting correlation rule: {e}")
        return create_response(data={"error": str(e)}, is_error=True)
    except Exception as e:
        logger.exception(f"Failed to insert correlation rule: {e}")
        return create_response(data={"error": str(e)}, is_error=True)


class CorrelationRulesModule(BaseModule):
    """
    Module for managing XSIAM Correlation Rules.

    This module provides comprehensive correlation rule management capabilities,
    enabling creation and maintenance of custom XQL-based detection rules in XSIAM.
    Correlation rules continuously analyze security data to detect threats and
    generate alerts when suspicious patterns are identified.

    Correlation rules are the foundation of custom threat detection in XSIAM,
    allowing security teams to:
    - Implement organization-specific detections
    - Deploy custom threat intelligence
    - Detect multi-stage attacks
    - Monitor for policy violations
    - Create behavioral analytics
    - Automate alert generation

    Tools provided:
        - insert_correlation_rule: Create or update XQL-based detection rules
    """

    def register_tools(self):
        self._add_tool(insert_correlation_rule)

    def register_resources(self):
        pass

    def __init__(self, mcp: FastMCP):
        super().__init__(mcp)
